### ISSUE TITLE
subghz chat error

### ISSUE THREAD

**Issue by qqmajikpp** [ranchordo/flipperzero-cli-bridge#2]
when sending the command:
subghz chat
the app replies:
other application is running, close it first

using a real console and sending the same command opens the chat

**Comment by ranchordo** [comment]
Sorry for taking so long to get to this, it should be fixed now in release v1.2. In the release description, there's some more info about what broke if you're curious, essentially it was an issue with the latest firmware versions. Please let me know if it still doesn't work. Thanks!
