### ISSUE TITLE
API Version

### ISSUE THREAD

**Issue by Phantom912** [ranchordo/flipperzero-cli-bridge#3]
I don't believe this is been Updated
 for the newest version

**Comment by TheKerevas** [comment]
To me with the latest version  0.83.1 appears API error, to my friend with Xtreme 0.46 firmware it works but he says there is an app running and I have to close it to start the command

**Comment by TheKerevas** [comment]
@ranchordo please we look forward to your reply

**Comment by ranchordo** [comment]
Hi, sorry, I'm currently away with limited internet access and no Flipper to test updates on. Release v1.2 is built for firmware 0.84 onward, so try release v1.1 in the meantime for 0.83.1. Your friend with Xtreme 0.46 may have an API that matches that of 0.84 or later, but the loader struct layout may still be on the older version, so v1.1 might work for them as well.

Given that this is a point of failure, I'm planning on building a more intelligent system for unlocking the loader that's more tolerant, but I can't do much until a couple of days from now (apologies), and I'll keep this issue open. Thanks for your patience!

**Comment by TheKerevas** [comment]
> Hi, sorry, I'm currently away with limited internet access and no Flipper to test updates on. Release v1.2 is built for firmware 0.84 onward, so try release v1.1 in the meantime for 0.83.1. Your friend with Xtreme 0.46 may have an API that matches that of 0.84 or later, but the loader struct layout may still be on the older version, so v1.1 might work for them as well.
> 
> Given that this is a point of failure, I'm planning on building a more intelligent system for unlocking the loader that's more tolerant, but I can't do much until a couple of days from now (apologies), and I'll keep this issue open. Thanks for your patience!

Thanks for the reply, at the moment I don't have the Flipper with me, my friend with Xtreme 0.46 tried the 1.1 and has the same error as the 1.2. However I need it to work because with the CLI I want to try the vibro if it works because I can't get it to work anymore and I want to have definitive confirmation that it's a hardware problem

**Comment by ranchordo** [comment]
Oh wait, looks like in the newer firmware versions, there's a new way to manipulate the loader lock state, so the current approach won't work. Sorry for not noticing that, and I also realized that v1.2 is built for 0.82 onward, not 0.84. Apologies for the confusion, and I should be able to implement and test the new loader unlock at some point tomorrow.

**Comment by TheKerevas** [comment]
> 

In fact it seemed strange to me. Thank you very much, if you give me the opportunity to test the vibro as soon as possible, I will understand better what to do. I contacted support and they are not responding after that days, if it continues like this, I'll fix it myself...

**Comment by ranchordo** [comment]
There's probably a good reason why you're not doing this, but if you do want to test vibro functionality, you could just connect your flipper via USB-C and access the CLI the normal way.

**Comment by TheKerevas** [comment]
> 

I don't know how to do it, the only simple one I've found is your fap 🤣

**Comment by ranchordo** [comment]
I think you should be able to access the CLI via [lab.flipper.net/](https://lab.flipper.net/), which might be the easiest option at this point.

**Comment by TheKerevas** [comment]
> I think you should be able to access the CLI via [lab.flipper.net/](https://lab.flipper.net/), which might be the easiest option at this point.

As soon as I'm home with Flipper I try, I hope to succeed. Thank you very much

**Comment by ranchordo** [comment]
No problem, thanks for bringing my attention to the change in loader behavior.

**Comment by TheKerevas** [comment]
> No problem, thanks for bringing my attention to the change in loader behavior.

I managed to use CLI from the site, putting vibro 1 Flipper doesn't emit any vibration, so I think it's a hardware problem :(

**Comment by ranchordo** [comment]
Loader issues and API version should finally be fixed now in release v1.3, thank you all for your patience.
