### ISSUE TITLE
Current versiou unusable in OFW

### ISSUE THREAD

**Issue by Storby42** [ranchordo/flipperzero-cli-bridge#5]
Returns error "Other applicatuin is running, please close it first" to all commands

**Comment by ranchordo** [comment]
Should be fixed now in release v1.3. The newer firmware versions and API changes modified how the loader service keeps track of the running apps internally, but the app should be able to figure that out now. Please let me know if it still doesn't work. Thanks!

**Comment by Storby42** [comment]
Thank you for all your development work!

**Comment by ranchordo** [comment]
You're welcome, thank you for helping me.
