### ISSUE TITLE
don't work, FZ Crash

### ISSUE THREAD

**Issue by djix68030** [ranchordo/flipperzero-cli-bridge#6]
Hi @ranchordo, when I launch the app, I have a message "API mismatch, this app might not work correctly continue anyway ? if I continue a keyboard appear on my FZ (may be to store a session's name) and if I press up/right/left/down or any other button,the flipper crash
FZ Firmware is : UNLSHD-064N

Regards, 

Djix68030

**Comment by ranchordo** [comment]
Hi,
Sorry about this, it should be fixed now in release v1.4, I just had to rebuild it against the newest firmware. I have tested it on unlshd-065e, and it seems to be working. Please let me know if you are still experiencing problems.

Thanks!

**Comment by djix68030** [comment]
Perfect Jay, it works also with UNLSHD-064N !! 

I bought an ESP32-S3 DevKitC-1 to do a "wifi devboard like" with Marauder on.
solder and test tonight (France Time Zone) 
;-) 
this is my home made NRF24 board:
![NRF24_board_v1 0](https://github.com/ranchordo/flipperzero-cli-bridge/assets/36102396/d5227cfe-caec-47c4-9cd4-6af9a21cc02d)

**Comment by ranchordo** [comment]
Awesome, glad to hear that it works!

Out of curiosity, were you planning to run Marauder directly, or build your own ESP32 wifi toolkit? If you are planning to build your own, do you plan to use UART for the flipper communication (like Marauder), or something like SPI/I2C and integrate it more closely with a flipper app?

**Comment by djix68030** [comment]
I've had my FZ for a week! I know how to read code, but don't have the skills to create what I want :-( for the moment I'm just testing Marauder directly in UART, in France the FZ community is very small, and the only people who use the FZ stupidly copy and paste without understanding how the code works, the FZ is very powerful, I have fun like a teenager (even if I got it for my 51st birthday :-), in any case very happy to have an exchange with someone "technically strong" is so rare, let's stay in touch... ;-)
can you tell me how I can open a terminal (windows or Linux) to access the Flipper CLI? I tested with Putty and tio on Linux, it waits, but nothing
with tio:
![image](https://github.com/ranchordo/flipperzero-cli-bridge/assets/36102396/f1828b1d-6a2d-47ee-9066-7354c439c860)
with putty:
![image](https://github.com/ranchordo/flipperzero-cli-bridge/assets/36102396/780c8b92-517b-474b-aa63-cd5cf109ff33)

**Comment by djix68030** [comment]
I'm stupid...I'm on a linux VM, and my USB device wasn't activate to be used by the VM...
![image](https://github.com/ranchordo/flipperzero-cli-bridge/assets/36102396/07d6c8e9-974f-4237-a8c8-be35c670f764)
![1697660290626](https://github.com/ranchordo/flipperzero-cli-bridge/assets/36102396/e76b31e7-f1eb-4dec-824e-d1e34d4a2982)
